#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ast.h" // Assuming ast.h defines all AST node types and ValueType enum

// Lexer functions and variables
extern int yylex();
extern int line_num; // Ensure these are correctly defined and updated in scanner.l
extern int col_num;  // Ensure these are correctly defined and updated in scanner.l
extern FILE* yyin;

// Error handling function
void yyerror(const char* s);

// Root of the AST
AST_Node* ast_root = NULL;

// Helper structure for building a list of values in the parser
typedef struct ValueHolder {
    Value_Node value_item;      // The actual Value_Node (copied)
    struct ValueHolder* next;
} ValueHolder;

// Helper functions (can be defined below yyparse or in a separate .c file)
// Pair_Node* create_pair_list(Pair_Node* first, Pair_Node* rest); // Original, not used by current grammar for pairs
// Value_Node* create_value_list(Value_Node* first, Value_Node* rest, int* count); // Original, will be replaced by ValueHolder logic


#line 32 "parser.y"
typedef union {
    char* string_val;       // From STRING token
    double number_val;      // From NUMBER token
    int boolean_val;        // From BOOLEAN token (0 or 1)
    // AST specific structures
    struct AST_Node* ast_node;
    struct Object_Node* object_node;
    struct Array_Node* array_node;
    struct Pair_Node* pair_node;
    struct Value_Node* value_node_ptr; // For individual Value_Node* returned by 'value' and 'array_value' rules
    struct ValueHolder* value_holder_list; // For the list of values in an array
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	STRING	258
#define	NUMBER	259
#define	BOOLEAN	260
#define	NUL	261


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int STRING;
static const int NUMBER;
static const int BOOLEAN;
static const int NUL;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,STRING=258
	,NUMBER=259
	,BOOLEAN=260
	,NUL=261


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::STRING=258;
const int YY_parse_CLASS::NUMBER=259;
const int YY_parse_CLASS::BOOLEAN=260;
const int YY_parse_CLASS::NUL=261;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		28
#define	YYFLAG		-32768
#define	YYNTBASE	13

#define YYTRANSLATE(x) ((unsigned)(x) <= 261 ? yytranslate[x] : 21)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     9,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    10,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    11,     2,    12,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     7,     2,     8,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     9,    11,    15,    19,    22,    26,    28,
    32,    34,    36,    38,    40,    42,    44
};

static const short yyrhs[] = {    20,
     0,     7,     8,     0,     7,    15,     8,     0,    16,     0,
    16,     9,    15,     0,     3,    10,    20,     0,    11,    12,
     0,    11,    18,    12,     0,    19,     0,    18,     9,    19,
     0,    20,     0,    14,     0,    17,     0,     3,     0,     4,
     0,     5,     0,     6,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    67,   121,   124,   140,   144,   151,   163,   166,   233,   241,
   259,   265,   271,   277,   283,   289,   295
};

static const char * const yytname[] = {   "$","error","$illegal.","STRING","NUMBER",
"BOOLEAN","NUL","'{'","'}'","','","':'","'['","']'","json","object","pairs",
"pair","array","values","array_value","value",""
};
#endif

static const short yyr1[] = {     0,
    13,    14,    14,    15,    15,    16,    17,    17,    18,    18,
    19,    20,    20,    20,    20,    20,    20
};

static const short yyr2[] = {     0,
     1,     2,     3,     1,     3,     3,     2,     3,     1,     3,
     1,     1,     1,     1,     1,     1,     1
};

static const short yydefact[] = {     0,
    14,    15,    16,    17,     0,     0,    12,    13,     1,     0,
     2,     0,     4,     7,     0,     9,    11,     0,     3,     0,
     0,     8,     6,     5,    10,     0,     0,     0
};

static const short yydefgoto[] = {    26,
     7,    12,    13,     8,    15,    16,    17
};

static const short yypact[] = {     8,
-32768,-32768,-32768,-32768,    13,    -2,-32768,-32768,-32768,    -4,
-32768,    -1,    15,-32768,    11,-32768,-32768,     8,-32768,     5,
     8,-32768,-32768,-32768,-32768,    17,    22,-32768
};

static const short yypgoto[] = {-32768,
-32768,     6,-32768,-32768,-32768,     4,     0
};


#define	YYLAST		26


static const short yytable[] = {     9,
     1,     2,     3,     4,     5,    18,    19,    10,     6,    14,
     1,     2,     3,     4,     5,    10,    27,    23,     6,    21,
    11,    28,    22,    20,    25,    24
};

static const short yycheck[] = {     0,
     3,     4,     5,     6,     7,    10,     8,     3,    11,    12,
     3,     4,     5,     6,     7,     3,     0,    18,    11,     9,
     8,     0,    12,     9,    21,    20
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 67 "parser.y"
{ // $1 is a Value_Node* (heap-allocated by the 'value' rule)
        ast_root = create_ast_node(NODE_NULL); // Create a shell, type will be set
        if (yyvsp[0].value_node_ptr != NULL) {
            // Transfer ownership of contents from the Value_Node pointed to by $1
            // to ast_root. The ast_root itself is an AST_Node.
            switch (yyvsp[0].value_node_ptr->type) {
                case VALUE_OBJECT:
                    ast_root->type = NODE_OBJECT;
                    ast_root->object = yyvsp[0].value_node_ptr->object_val; // Transfer ownership of Object_Node*
                    yyvsp[0].value_node_ptr->object_val = NULL; // Avoid double free if $1 is complexly freed later
                    break;
                case VALUE_ARRAY:
                    ast_root->type = NODE_ARRAY;
                    ast_root->array = yyvsp[0].value_node_ptr->array_val;   // Transfer ownership of Array_Node*
                    yyvsp[0].value_node_ptr->array_val = NULL;
                    break;
                case VALUE_STRING:
                    ast_root->type = NODE_STRING;
                    ast_root->string_val = yyvsp[0].value_node_ptr->string_val; // Transfer ownership of char*
                    yyvsp[0].value_node_ptr->string_val = NULL;
                    break;
                case VALUE_NUMBER:
                    ast_root->type = NODE_NUMBER;
                    ast_root->number_val = yyvsp[0].value_node_ptr->number_val;
                    break;
                case VALUE_BOOLEAN:
                    ast_root->type = NODE_BOOLEAN;
                    ast_root->boolean_val = yyvsp[0].value_node_ptr->boolean_val;
                    break;
                case VALUE_NULL:
                    ast_root->type = NODE_NULL;
                    break;
                default:
                    yyerror("Unknown value type in json rule");
                    // Potentially free $1 and ast_root before aborting
                    free(yyvsp[0].value_node_ptr);
                    free(ast_root); // or free_ast(ast_root) if partially populated
                    ast_root = NULL;
                    YYABORT;
            }
            free(yyvsp[0].value_node_ptr); // Free the Value_Node struct itself, its contents are now owned by ast_root
        } else {
            // This case should ideally not be reached if 'value' always returns a valid pointer or YYABORTs.
            // If it can be NULL, ast_root remains NODE_NULL or an empty default.
            // free(ast_root); // If $1 is NULL, ast_root might be an empty shell.
            // ast_root = create_ast_node(NODE_NULL); // Or ensure it's a valid empty AST
            yyerror("Internal error: value rule returned NULL to json rule");
            free(ast_root); ast_root = NULL; YYABORT;
        }
        yyval.ast_node = ast_root;
    ;
    break;}
case 2:
#line 121 "parser.y"
{
        yyval.object_node = create_object_node();
    ;
    break;}
case 3:
#line 124 "parser.y"
{ // $2 is Pair_Node* (list of pairs)
        yyval.object_node = create_object_node();
        // Add pairs to the object. The 'pairs' rule returns a linked list.
        Pair_Node* current_pair_item = yyvsp[-1].pair_node;
        while (current_pair_item) {
            Pair_Node* next_pair_item = current_pair_item->next;
            current_pair_item->next = NULL; // Detach from list before adding
            add_pair_to_object(yyval.object_node, current_pair_item);
            current_pair_item = next_pair_item;
        }
        // The Pair_Node items themselves are now owned by the Object_Node.
        // The list structure of $2 is consumed.
    ;
    break;}
case 4:
#line 140 "parser.y"
{ // $1 is Pair_Node*
        yyval.pair_node = yyvsp[0].pair_node;
        yyval.pair_node->next = NULL; // Ensure it's a single-item list initially
    ;
    break;}
case 5:
#line 144 "parser.y"
{ // $1 is Pair_Node*, $3 is Pair_Node* (rest of the list)
        yyvsp[-2].pair_node->next = yyvsp[0].pair_node; // Prepend $1 to the list $3
        yyval.pair_node = yyvsp[-2].pair_node;
    ;
    break;}
case 6:
#line 151 "parser.y"
{ // $1 is char* (key), $3 is Value_Node* (value wrapper)
        // create_pair_node takes (char* key, Value_Node value_struct).
        // It does NOT take Value_Node*. So we dereference $3.
        // The key ($1) is from yylval.string_val, processed by scanner's process_string (heap).
        // The Value_Node from $3 contains the actual data (e.g., Object_Node*, char*).
        yyval.pair_node = create_pair_node(yyvsp[-2].string_val, *yyvsp[0].value_node_ptr); // $1 (key) is now owned by Pair_Node.
                                        // Contents of *$3 are copied or pointers transferred by create_string/object/array_value logic.
        free(yyvsp[0].value_node_ptr); // Free the Value_Node struct wrapper pointed to by $3. Its contents are now part of the Pair_Node.
    ;
    break;}
case 7:
#line 163 "parser.y"
{
        yyval.array_node = create_array_node(0);
    ;
    break;}
case 8:
#line 166 "parser.y"
{ // $2 is ValueHolder* (linked list of ValueHolder)
        int count = 0;
        ValueHolder* current_vh = yyvsp[-1].value_holder_list;
        while (current_vh) {
            count++;
            current_vh = current_vh->next;
        }

        yyval.array_node = create_array_node(count); // $$ is Array_Node*
        current_vh = yyvsp[-1].value_holder_list; // Reset to head of list

        // The list built by 'values' rule is in reverse parse order.
        // Example: [a, b, c] -> values rule: c -> b -> a (holder(a) is head)
        // So, to fill array elements in correct order [a,b,c], iterate list and fill from 0 to count-1
        // OR, fill from count-1 down to 0.
        // Let's assume 'values' rule: value ',' values results in $1 (new head) -> $3 (tail)
        // So, [a,b,c] -> holder(a) -> holder(b) -> holder(c). Iterate normally.

        for (int i = 0; i < count; i++) {
            if (!current_vh) { // Should not happen if count is correct
                yyerror("Internal error: Mismatch in array value count");
                // Free $$ (Array_Node) and any already added elements if possible
                // For simplicity, YYABORT. Proper cleanup is complex here.
                // free_ast( (AST_Node*) $$ ); // This is wrong, $$ is Array_Node*
                // Need to free Array_Node $$ and its elements if partially filled.
                // For now, rely on higher level free_ast(ast_root) on error exit.
                YYABORT;
            }
            // add_element_to_array takes (Array_Node*, int index, Value_Node value_struct)
            // current_vh->value_item is a Value_Node struct.
            add_element_to_array(yyval.array_node, i, current_vh->value_item); 
            // The contents of current_vh->value_item (like char* for string, Object_Node*)
            // are now "owned" by the Array_Node due to the copy/transfer in add_element_to_array.
            // Or rather, add_element_to_array copies the Value_Node struct. If that struct contains
            // pointers (string_val, object_val, array_val), those pointers are copied.
            // The actual data pointed to (the string, the object, the array) must have its ownership
            // correctly managed. The Value_Node itself (current_vh->value_item) is on the ValueHolder's stack/struct.

            ValueHolder* temp_vh = current_vh;
            current_vh = current_vh->next;
            // We must NOT free contents of temp_vh->value_item here if they were transferred to Array_Node.
            // The Value_Node structs created by 'value' rule are copied into ValueHolder.
            // The original Value_Node* from 'value' rule was freed when creating the ValueHolder.
            // So, temp_vh->value_item's contents (pointers to string/object/array data) are the ones
            // that are now also pointed to by the Array_Node.
            // This is fine as long as add_element_to_array correctly handles the Value_Node struct copy.
            // The ast.c create_xxx_value functions ensure the Value_Node struct is properly formed.
            free(temp_vh); // Free the ValueHolder list node itself.
        }
        if (current_vh != NULL) { // Should be NULL if all processed
             yyerror("Internal error: Array values list not fully processed.");
             // Free remaining ValueHolder items to prevent leaks
             while(current_vh) {
                 ValueHolder* temp_vh = current_vh;
                 current_vh = current_vh->next;
                 // Important: If value_item contains heap data (string, object, array)
                 // that was NOT successfully transferred to the final AST (e.g. due to error),
                 // it needs to be freed here. However, with current logic, they *are* transferred.
                 // So, only free the holder.
                 // free_value_node_contents(&temp_vh->value_item); // ONLY if data not transferred
                 free(temp_vh);
             }
        }
    ;
    break;}
case 9:
#line 233 "parser.y"
{ // $1 is Value_Node* (heap-allocated wrapper)
        ValueHolder* vh = (ValueHolder*)malloc(sizeof(ValueHolder));
        if (!vh) { yyerror("malloc failed for ValueHolder"); YYABORT; }
        vh->value_item = *yyvsp[0].value_node_ptr; // Copy the Value_Node struct
        vh->next = NULL;
        yyval.value_holder_list = vh;
        free(yyvsp[0].value_node_ptr); // Free the Value_Node* wrapper, its contents are now in vh->value_item
    ;
    break;}
case 10:
#line 241 "parser.y"
{ // $1 is ValueHolder* (list so far), $3 is Value_Node* (new item wrapper)
        ValueHolder* new_vh = (ValueHolder*)malloc(sizeof(ValueHolder));
        if (!new_vh) { yyerror("malloc failed for new ValueHolder"); YYABORT; }
        new_vh->value_item = *yyvsp[0].value_node_ptr; // Copy the Value_Node struct
        new_vh->next = NULL;

        // Append new_vh to the end of the list $1
        ValueHolder* current_vh = yyvsp[-2].value_holder_list;
        while(current_vh->next != NULL) {
            current_vh = current_vh->next;
        }
        current_vh->next = new_vh;
        yyval.value_holder_list = yyvsp[-2].value_holder_list; // Return the original head of the list
        free(yyvsp[0].value_node_ptr); // Free the Value_Node* wrapper
    ;
    break;}
case 11:
#line 259 "parser.y"
{ // $1 is Value_Node*
        yyval.value_node_ptr = yyvsp[0].value_node_ptr; // Pass through the Value_Node*
    ;
    break;}
case 12:
#line 265 "parser.y"
{ // $1 is Object_Node*
        Value_Node* vn = (Value_Node*)malloc(sizeof(Value_Node));
        if (!vn) { yyerror("malloc failed for Value_Node (object)"); YYABORT; }
        *vn = create_object_value(yyvsp[0].object_node); // create_object_value returns a Value_Node struct
        yyval.value_node_ptr = vn;
    ;
    break;}
case 13:
#line 271 "parser.y"
{ // $1 is Array_Node*
        Value_Node* vn = (Value_Node*)malloc(sizeof(Value_Node));
        if (!vn) { yyerror("malloc failed for Value_Node (array)"); YYABORT; }
        *vn = create_array_value(yyvsp[0].array_node);
        yyval.value_node_ptr = vn;
    ;
    break;}
case 14:
#line 277 "parser.y"
{ // $1 is char* (heap-allocated by scanner's process_string)
        Value_Node* vn = (Value_Node*)malloc(sizeof(Value_Node));
        if (!vn) { yyerror("malloc failed for Value_Node (string)"); free(yyvsp[0].string_val); YYABORT; }
        *vn = create_string_value(yyvsp[0].string_val); // $1 (char*) is now owned by this Value_Node's contents
        yyval.value_node_ptr = vn;
    ;
    break;}
case 15:
#line 283 "parser.y"
{ // $1 is double
        Value_Node* vn = (Value_Node*)malloc(sizeof(Value_Node));
        if (!vn) { yyerror("malloc failed for Value_Node (number)"); YYABORT; }
        *vn = create_number_value(yyvsp[0].number_val);
        yyval.value_node_ptr = vn;
    ;
    break;}
case 16:
#line 289 "parser.y"
{ // $1 is int (0 or 1)
        Value_Node* vn = (Value_Node*)malloc(sizeof(Value_Node));
        if (!vn) { yyerror("malloc failed for Value_Node (boolean)"); YYABORT; }
        *vn = create_boolean_value(yyvsp[0].boolean_val); // $1 is a simple int, copied
        yyval.value_node_ptr = vn;
    ;
    break;}
case 17:
#line 295 "parser.y"
{
        Value_Node* vn = (Value_Node*)malloc(sizeof(Value_Node));
        if (!vn) { yyerror("malloc failed for Value_Node (null)"); YYABORT; }
        *vn = create_null_value();
        yyval.value_node_ptr = vn;
    ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 303 "parser.y"


void yyerror(const char* s) {
    // Make sure line_num and col_num are accurately updated by the lexer for all tokens
    fprintf(stderr, "Parser Error: %s at line %d, column %d\n", s, line_num, col_num);
    // Consider a more graceful exit or error recovery if this is part of a larger system.
    // For a standalone tool, exit is common.
    // exit(EXIT_FAILURE); // YYABORT might be preferred within parser actions
}

// If create_pair_list and create_value_list were used, their definitions would go here.
// Since they are not used by the revised grammar, they can be removed.
